apiVersion: batch/v1
kind: Job
metadata:
    name: database-migration
    annotations:
        "helm.sh/hook": pre-install,pre-upgrade
        "helm.sh/hook-weight": "-5"
        "helm.sh/hook-delete-policy": hook-succeeded
spec:
    template:
        spec:
            restartPolicy: Never
            containers:
                - name: flyway
                  image: local/finance-app-migration
                  command: [ "/flyway/flyway" ]  # Overrides the default entrypoint
                  args:
                      - info
                      - repair
                      - migrate
                      - info
                  env:
                      - name: FLYWAY_URL
                        value: 'jdbc:postgresql://postgresql-service.db.svc.cluster.local:5432/finance-app-database'
                      - name: FLYWAY_DEFAULT_SCHEMA
                        value: 'finance_app'
                      - name: FLYWAY_USER
                        value: 'postgres'
                      - name: FLYWAY_PASSWORD
                        value: 'postgres'
                      - name: FLYWAY_LOCATIONS
                        value: 'filesystem:/flyway/db/migration'
