name: Build - finance-app-backend

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Pegamos o commit anterior para comparação

      - name: Check if changes were made in finance-app-backend
        id: check_changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "Arquivos modificados: $CHANGED_FILES"
          
          if echo "$CHANGED_FILES" | grep -q "^finance-app-backend/"; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

      - name: Stop if no changes in finance-app-backend
        if: env.changes == 'false'
        run: echo "No changes in finance-app-backend, skipping build." && exit 0

      - name: Set up Java version
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '21'

      # TODO fix tests
      - name: Build with Maven
        working-directory: finance-app-backend
        run: mvn clean install -DskipTests

#      - name: Upload artifact for deployment job
#        uses: actions/upload-artifact@v4.3.3
#        with:
#          name: java-app
#          path: 'finance-app-backend/target/*.jar'