name: Build - finance-app-backend

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - develop
    paths:
      - 'finance-app-backend/**' # Only trigger if changes are inside finance-app-backend

  push:
    branches:
      - main
      - develop
    paths:
      - 'finance-app-backend/**' # Only trigger if changes are inside finance-app-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '21'

      # TODO fix tests
      - name: Build with Maven
        working-directory: finance-app-backend # Ensure Maven runs inside the backend folder
        run: mvn clean install -DskipTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4.3.3
        with:
          name: java-app
          path: 'finance-app-backend/target/*.jar'
