on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.changes.outputs.backend }}
      ui_changed: ${{ steps.changes.outputs.ui }}
    steps:
      - uses: actions/checkout@v4

      - name: Check changed folders
        id: changes
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }})

          echo "backend=false" >> $GITHUB_OUTPUT
          echo "ui=false" >> $GITHUB_OUTPUT

          if echo "$CHANGED_FILES" | grep -q "^backend/"; then
            echo "backend=true" >> $GITHUB_OUTPUT
          fi
          if echo "$CHANGED_FILES" | grep -q "^ui/"; then
            echo "ui=true" >> $GITHUB_OUTPUT
          fi

  build-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Backend
        working-directory: finance-app-backend
        run: mvn clean install -DskipTests

  build-ui:
    needs: detect-changes
    if: needs.detect-changes.outputs.ui_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build UI
        working-directory: finance-app-ui
        run: npm install && npm run build
